```python
from typing import Any, Dict

from fastapi import APIRouter, HTTPException, status
from fastapi.responses import JSONResponse

router = APIRouter()


@router.get(
    "/openapi.yaml",
    response_model=Dict[str, Any],
    summary="Retrieve OpenAPI/Swagger documentation",
    description="This endpoint retrieves the OpenAPI/Swagger documentation in YAML format.",
    response_description="OpenAPI/Swagger documentation in YAML format.",
    tags=["Documentation"],
)
async def get_openapi_yaml() -> JSONResponse:
    """
    Retrieve the OpenAPI/Swagger documentation.

    Returns:
        JSONResponse: The OpenAPI/Swagger documentation in YAML format.

    Raises:
        HTTPException: If there is an error retrieving the documentation.
    """
    try:
        with open("docs/openapi.yaml", "r") as f:
            openapi_content = f.read()

        # Convert YAML content to a dictionary for JSONResponse
        # Note: FastAPI automatically handles YAML content if you directly return it as a string,
        # but for demonstration and potential future processing, we'll parse it.
        # You might need to install PyYAML: pip install pyyaml
        import yaml

        openapi_dict = yaml.safe_load(openapi_content)

        return JSONResponse(content=openapi_dict, media_type="application/json")

    except FileNotFoundError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="OpenAPI documentation file not found.",
        )
    except yaml.YAMLError as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error parsing OpenAPI documentation: {e}",
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An unexpected error occurred: {e}",
        )
```