```python
from typing import Any, Dict

from fastapi import APIRouter, HTTPException, status
from fastapi.responses import JSONResponse

router = APIRouter()


@router.get(
    "/openapi.yaml",
    response_model=Dict[str, Any],
    summary="Retrieve OpenAPI/Swagger documentation",
    description="This endpoint retrieves the OpenAPI/Swagger documentation in YAML format.",
    response_description="OpenAPI/Swagger documentation in YAML format.",
    tags=["Documentation"],
    responses={
        status.HTTP_200_OK: {
            "description": "Successfully retrieved OpenAPI/Swagger documentation.",
            "content": {"application/x-yaml": {}},
        },
        status.HTTP_500_INTERNAL_SERVER_ERROR: {
            "description": "Internal server error occurred.",
        },
    },
)
async def get_openapi_yaml() -> JSONResponse:
    """
    Retrieve the OpenAPI/Swagger documentation in YAML format.

    Returns:
        JSONResponse: OpenAPI/Swagger documentation in YAML format.

    Raises:
        HTTPException: If an error occurs while retrieving the documentation.
    """
    try:
        with open("docs/openapi.yaml", "r") as f:
            openapi_yaml_content = f.read()
        return JSONResponse(content=openapi_yaml_content, media_type="application/x-yaml")
    except FileNotFoundError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="OpenAPI documentation file not found.",
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while retrieving the OpenAPI documentation: {e}",
        )
```